---
title: "TSP Energy Supply Modeling"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
---



```{r Data Setup, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}

# Load packages 
my_packages <- c("tidyverse", "vroom" , "timetk", "janitor" , "glue" , "tsibble" , "tidytext","lubridate", "fable", "tsibbledata", "ggplot2", "forecast", "tseries", "rio", "zoo", "readxl", "tsibbledata", "knitr", "formattable", "scales", "kable", "kableExtra", "dplyr")   

invisible( lapply(my_packages, require, character.only = TRUE))

#Set up environment 
place <- "Home"  #Where are we working today. 
# place <- "work"

if (place == "Home"){setwd("C:/Users/paulr/Documents/R/ElectricSupplyOptions")} else {setwd("C:/Users/prode/Documents/R/ElectricSupplyOptions")}

if (!file.exists("data")) { dir.create("data")}
if (!file.exists("NYSISO_data")) { dir.create("NYSISO_data")}

rm(place, my_packages ) #Clean up

options(dplyr.summarise.inform = FALSE)  # Suppress text in Knit printout. 



# Read in data

do.call(rbind, lapply(list.files(pattern = ".csv"), read_csv)) -> NYSISO_data
NYSISO_data$`Eastern Date Hour` <- ymd_hms(NYSISO_data$`Eastern Date Hour`)


# Plot data 

NYSISO_data %>% 
  ggplot(aes(x = `Eastern Date Hour`, y = `DAM Zonal LBMP`)) +
  geom_line() +
  stat_smooth(method = "lm", formula = y ~ x, show.legend = TRUE, inherit.aes = TRUE, )


#Trend by year
NYSISO_data %>% 
  group_by(Year = year(`Eastern Date Hour`)) %>% 
  summarise(LBMP_Avr = mean(`DAM Zonal LBMP`)) %>% 
  ggplot(aes(x = Year, y = LBMP_Avr)) +
  geom_line() +
  stat_smooth(method = "lm", formula = y ~ x, show.legend = TRUE, inherit.aes = TRUE, )


#Trend by Month
NYSISO_data %>% 
  mutate("YearMonth" = year(`Eastern Date Hour`) + month(`Eastern Date Hour`)/12) %>% 
  group_by(YearMonth) %>% 
  summarise(LBMP_Avr = mean(`DAM Zonal LBMP`)) %>% 
  ggplot(aes(x = YearMonth, y = LBMP_Avr)) +
  geom_line() +
  stat_smooth(method = "lm", formula = y ~ x, show.legend = TRUE, inherit.aes = TRUE, )

#Look at historical pricing ranges 
NYSISO_data %>% 
  group_by(Month = month(`Eastern Date Hour`)) %>% 
  summarise(LBMP_Avr = mean(`DAM Zonal LBMP`)) %>% 
  ggplot(aes(Month, LBMP_Avr, fill = LBMP_Avr )) +
  geom_bar(stat = "identity", position = "dodge")


#Look at yearly averages 
NYSISO_data %>% 
  group_by(Year = year(`Eastern Date Hour`)) %>% 
  summarise(LBMP_Avr = mean(`DAM Zonal LBMP`)) %>% 
  ggplot(aes(Year, LBMP_Avr, fill = LBMP_Avr )) +
  geom_bar(stat = "identity", position = "dodge")



```

ISO Market data from: https://www.nyiso.com/custom-reports


```{r Data Production, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}

"Comp520" <- read_excel("data/520 Madison.xlsx",skip = 1, col_types = c("date", "numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric" ) , col_names = c("TimeStamp", "A", "B", "C", "D", "E", "F", "G", "H"), na = "NA") %>% 
  mutate("Building" = "520 Madison Avenue", .before=1) %>%  
  mutate("Elect" = A + B + C + D + E + F + G + H, .keep = "unused")  
 
Comp520 %>% 
  select(TimeStamp) %>% 
  filter(minute(TimeStamp) == 0 & second(TimeStamp) == 0) -> Comp520a

Comp520a <- Comp520a[complete.cases(Comp520a),] 

Comp520 %>% 
  group_by(y = year(TimeStamp), m = month(TimeStamp),d = day(TimeStamp), h = hour(TimeStamp)) %>% 
  summarise( "Elect" = sum(Elect)) %>% 
  mutate(TimeStamp = paste(y, m, d, sep = '-')) %>% 
  mutate(TimeStamp = paste( TimeStamp, h, sep = " ")) %>% 
  mutate(TimeStamp = paste( TimeStamp, ':00:00', sep = "")) %>% 
  mutate(TimeStamp = ymd_hms(TimeStamp)) -> Comp520

Comp520[c(5:6)] -> Comp520

rm(Comp520a, Comp520b, Comp520c ) #Clean up

colnames(NYSISO_data)[1] <- "TimeStamp"

inner_join(Comp520, NYSISO_data, by = "TimeStamp") %>% 
  na.omit() -> ISOCOMP_data
ISOCOMP_data <- unique(ISOCOMP_data)
ISOCOMP_data %>% 
  select(c(2,1,6)) -> ISOCOMP_data
colnames(ISOCOMP_data) <- c("TimeStamp", "Energy", "LBMP")

ISOCOMP_data %>% 
  ggplot(aes(x = `TimeStamp`, y = Energy)) +
  geom_line() +
  geom_line(aes(y = LBMP*10, color = "red"))
  stat_smooth(method = "lm", formula = y ~ x, show.legend = TRUE, inherit.aes = TRUE, ) 


  NYSISO_data %>% 
  ggplot(aes(x = `TimeStamp`, y = `DAM Zonal LBMP`)) +
  geom_line() +
  stat_smooth(method = "lm", formula = y ~ x, show.legend = TRUE, inherit.aes = TRUE, )

  Comp520 %>% 
      ggplot(aes(x = `TimeStamp`, y = `Elect`)) +
  geom_line() +
  stat_smooth(method = "lm", formula = y ~ x, show.legend = TRUE, inherit.aes = TRUE, )
  
  ISOCOMP_data %>% 
    mutate('TotalCost' = ((0.5 * Energy /1000 * LBMP) + (0.5 * Energy / 1000 * 85.16))/Energy * 1000) -> ISOCOMP_data
  
  ISOCOMP_data %>% 
      ggplot(aes(x = `TimeStamp`, y = LBMP)) +
  geom_line(color = "grey") +
  geom_line(aes(y = TotalCost), color = "green") +
  theme_classic()
    
```


